import React, { useState } from 'react';
import { Download, Loader2 } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import remarkMath from 'remark-math';
import rehypeKatex from 'rehype-katex';
import api from '../utils/api';
import { preprocessLatex } from '../utils/latexHelper';

const PDFExport = ({ summary, quizData, flashcards }) => {
  const [isExporting, setIsExporting] = useState(false);
  
  const handleDownload = async () => {
    // 1. Get the element we want to print
    const element = document.getElementById('full-content-export');
    
    // Debugging: Check if element exists
    if (!element) {
      alert("❌ Error: Could not find the content to print.");
      return;
    }

    setIsExporting(true);

    try {
      // 1. Verify download quota with backend
      try {
        await api.post('/track-download', {
          type: 'summary',
          title: 'Study Guide'
        });
      } catch (quotaErr) {
        if (quotaErr.response?.status === 402) {
          alert(quotaErr.response.data.detail || "Daily download limit reached! Normal users get 6 downloads/day, Pro gets 15/day, and Premium gets Unlimited.");
          return;
        }
      }

      // Dynamically import html2pdf to prevent build-time or mount-time crashes
      const html2pdfModule = await import('html2pdf.js');
      const html2pdf = html2pdfModule.default;

      // 2. Set PDF options
      const opt = {
        margin:       [10, 10, 10, 10],
        filename:     'Florix_Study_Material.pdf',
        image:        { type: 'jpeg', quality: 0.98 },
        html2canvas:  { scale: 2, useCORS: true },
        jsPDF:        { unit: 'mm', format: 'a4', orientation: 'portrait' }
      };

      // 3. Generate
      console.log("Generating PDF...");
      await html2pdf().set(opt).from(element).save();
      console.log("PDF Done!");
    } catch (err) {
      alert("PDF Generation Error: " + err.message);
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <>
      {/* 1. THE VISIBLE BUTTON */}
      <button 
        onClick={handleDownload}
        disabled={isExporting}
        className="flex items-center gap-2 px-5 py-2.5 bg-indigo-600 hover:bg-indigo-700 disabled:opacity-50 text-white rounded-xl text-sm font-bold transition-all shadow-lg shadow-indigo-500/20"
      >
        {isExporting ? <Loader2 className="animate-spin" size={18} /> : <Download size={18}/>}
        {isExporting ? "Exporting..." : "PDF"}
      </button>

      {/* 2. THE HIDDEN CONTENT (Positioned off-screen so the user can't see it, but the PDF engine can) */}
      <div style={{ position: 'fixed', top: '-10000px', left: '-10000px', width: '800px', background: 'white', zIndex: -1 }}>
          <div id="full-content-export" className="p-10 text-black font-sans">
              
              {/* HEADER */}
              <div className="text-center mb-10 border-b-2 border-indigo-600 pb-4">
                  <h1 className="text-4xl font-extrabold text-indigo-700">Florix Study Material</h1>
                  <p className="text-gray-500 mt-2">Generated by AI Tutor</p>
              </div>

              {/* SUMMARY SECTION */}
              <section className="mb-10">
                  <h2 className="text-2xl font-bold mb-4 text-indigo-600 uppercase tracking-wide">Summary</h2>
                  <article className="prose prose-slate max-w-none text-gray-800">
                    <ReactMarkdown remarkPlugins={[remarkGfm, remarkMath]} rehypePlugins={[rehypeKatex]}>
                        {preprocessLatex(summary || "No summary available.")}
                    </ReactMarkdown>
                  </article>
              </section>

              {/* PAGE BREAK */}
              <div className="html2pdf__page-break"></div>

              {/* QUIZ SECTION */}
              {quizData && quizData.length > 0 && (
                  <section className="mb-10">
                      <h2 className="text-2xl font-bold mb-6 text-indigo-600 uppercase tracking-wide">Quiz Questions</h2>
                      {quizData.map((q, i) => (
                          <div key={i} className="mb-6 p-4 border border-gray-200 rounded-lg bg-gray-50 break-inside-avoid">
                              <p className="font-bold text-lg mb-3 text-gray-900">{i+1}. {q.question}</p>
                              <div className="ml-4 mb-3 space-y-1">
                                  {q.options.map((opt, j) => (
                                      <p key={j} className={`text-sm ${j === q.answer ? 'font-bold text-green-700' : 'text-gray-600'}`}>
                                          {j === q.answer ? '✓ ' : '○ '} {opt}
                                      </p>
                                  ))}
                              </div>
                          </div>
                      ))}
                  </section>
              )}

              {/* FLASHCARDS SECTION */}
              {flashcards && flashcards.length > 0 && (
                  <section>
                      <div className="html2pdf__page-break"></div>
                      <h2 className="text-2xl font-bold mb-6 text-indigo-600 uppercase tracking-wide mt-8">Flashcards</h2>
                      <div className="grid grid-cols-2 gap-4">
                          {flashcards.map((f, i) => (
                              <div key={i} className="p-4 border-2 border-indigo-50 rounded-lg bg-white break-inside-avoid">
                                  <p className="text-xs font-bold text-indigo-400 uppercase mb-1">Question</p>
                                  <p className="font-bold text-gray-800 mb-3">{f.front}</p>
                                  <hr className="my-2 border-gray-100"/>
                                  <p className="text-xs font-bold text-emerald-500 uppercase mb-1">Answer</p>
                                  <p className="text-gray-600 text-sm">{f.back}</p>
                              </div>
                          ))}
                      </div>
                  </section>
              )}
          </div>
      </div>
    </>
  );
};

export default PDFExport;